apiVersion: v1
kind: Service
metadata:
  name: game-service-db-service
  labels:
    app: game-service-db
spec:
  type: NodePort
  ports:
    - port: 20207
      targetPort: 5432
      nodePort: 30207
  type: NodePort
  selector:
    app: game-service-db