kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: game-service-db-pv-claim
  labels:
    app: game-service-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi