apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: game-engine-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: game-engine
  metrics:
    - type: Pods
      pods:
        metric:
          name: session_count
        target:
          averageValue: 2
          type: AverageValue