kind: PersistentVolume
apiVersion: v1
metadata:
  name: user-service-db-pv-volume
  labels:
    type: local
    app: user-service-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Data/UserServiceDB
    type: DirectoryOrCreate