apiVersion: v1
kind: Service
metadata:
  name: user-service-db-service
  labels:
    app: user-service-db
spec:
  type: NodePort
  ports:
    - port: 20205
      targetPort: 5432
      nodePort: 30205
  type: NodePort
  selector:
    app: user-service-db