kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-cache-pv-claim
  labels:
    app: redis-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi