kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-cache-pv-volume
  labels:
    type: local
    app: redis-cache
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Data/AuthServiceRedisCache
    type: DirectoryOrCreate