apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-service
  name: eureka-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
      - image: vkr-eureka-service
        imagePullPolicy: IfNotPresent
        envFrom:
            - configMapRef:
                name: eureka-service-config
        name: eureka-service