apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports: 
  - port: 20300
    protocol: TCP
    targetPort: 20300
    nodePort: 30300
  selector:
    app: api-gateway
  type: NodePort