kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: game-engine-controller-service-admin
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "delete"]