apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
  namespace: default
subjects:
- kind: Group
  name: game-service-controller-account
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: game-engine-controller-service-admin
  apiGroup: ""