apiVersion: v1
kind: Service
metadata:
  labels:
    app: game-engine-controller
  name: game-engine-controller-service
  namespace: default
spec:
  ports: 
  - port: 20600
    protocol: TCP
  selector:
    app: game-engine-controller